name: Test and Build Docker Image

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker image
              run: docker build -t my-app:latest .

            - name: Run tests inside the Docker image
              run: docker run --rm my-app:latest npm test

            - name: Log in to Docker Hub
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Tag and Push Docker Image (Conditional)
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                  docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
                  docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
                  docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
                  docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
